add_lunch_combo lineage_j7y17lte-userdebug
add_lunch_combo lineage_j7y17lte-eng
add_lunch_combo rr_j7y17lte-userdebug
add_lunch_combo rr_j7y17lte-eng
add_lunch_combo aosp_j7y17lte-eng
add_lunch_combo aosp_j7y17lte-userdebug
